/**
 * Subscription Factory
 *
 * Creates test subscription data for different tiers and states.
 */

const { admin } = require('../../src/config/firebase');

/**
 * Create subscription object
 *
 * @param {Object} overrides - Custom fields
 * @returns {Object} Subscription object
 */
function createSubscription(overrides = {}) {
  const defaults = {
    tier: 'free',
    status: 'active',
    last_synced: admin.firestore.FieldValue.serverTimestamp()
  };

  return { ...defaults, ...overrides };
}

/**
 * Create free tier subscription
 *
 * @param {Object} overrides - Custom fields
 * @returns {Object} Free tier subscription
 */
function createFreeSubscription(overrides = {}) {
  return createSubscription({
    tier: 'free',
    status: 'active',
    ...overrides
  });
}

/**
 * Create Pro tier subscription (paid)
 *
 * @param {Object} overrides - Custom fields
 * @returns {Object} Pro tier subscription
 */
function createProSubscription(overrides = {}) {
  return createSubscription({
    tier: 'pro',
    status: 'active',
    active_subscription_id: `sub_${Date.now()}`,
    ...overrides
  });
}

/**
 * Create Ultra tier subscription (paid)
 *
 * @param {Object} overrides - Custom fields
 * @returns {Object} Ultra tier subscription
 */
function createUltraSubscription(overrides = {}) {
  return createSubscription({
    tier: 'ultra',
    status: 'active',
    active_subscription_id: `sub_${Date.now()}`,
    ...overrides
  });
}

/**
 * Create subscription with testing override
 *
 * @param {string} tier - 'pro' or 'ultra'
 * @param {number} daysValid - Days until override expires
 * @param {Object} overrides - Custom fields
 * @returns {Object} Subscription with override
 */
function createSubscriptionWithOverride(tier = 'pro', daysValid = 90, overrides = {}) {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + (daysValid * 24 * 60 * 60 * 1000));

  return createSubscription({
    tier,
    status: 'active',
    override: {
      type: 'testing',
      tier_id: tier,
      granted_by: 'test-factory',
      granted_at: admin.firestore.FieldValue.serverTimestamp(),
      expires_at: admin.firestore.Timestamp.fromDate(expiresAt),
      reason: 'Generated by test factory'
    },
    ...overrides
  });
}

/**
 * Create subscription with beta tester override
 *
 * @param {string} tier - 'pro' or 'ultra'
 * @param {number} daysValid - Days until override expires
 * @param {Object} overrides - Custom fields
 * @returns {Object} Subscription with beta override
 */
function createBetaSubscription(tier = 'ultra', daysValid = 180, overrides = {}) {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + (daysValid * 24 * 60 * 60 * 1000));

  return createSubscription({
    tier,
    status: 'active',
    override: {
      type: 'beta_tester',
      tier_id: tier,
      granted_by: 'admin',
      granted_at: admin.firestore.FieldValue.serverTimestamp(),
      expires_at: admin.firestore.Timestamp.fromDate(expiresAt),
      reason: 'Beta tester access'
    },
    ...overrides
  });
}

/**
 * Create trial subscription
 *
 * @param {number} daysRemaining - Days until trial expires
 * @param {Object} overrides - Custom fields
 * @returns {Object} Trial subscription
 */
function createTrialSubscription(daysRemaining = 25, overrides = {}) {
  const now = new Date();
  const trialEnd = new Date(now.getTime() + (daysRemaining * 24 * 60 * 60 * 1000));
  const trialStart = new Date(now.getTime() - ((30 - daysRemaining) * 24 * 60 * 60 * 1000));

  return {
    subscription: createSubscription({
      tier: 'pro',
      status: 'trial'
    }),
    trial: {
      ends_at: admin.firestore.Timestamp.fromDate(trialEnd),
      started_at: admin.firestore.Timestamp.fromDate(trialStart),
      is_active: true,
      tier_id: 'pro'
    },
    trialEndsAt: admin.firestore.Timestamp.fromDate(trialEnd),
    ...overrides
  };
}

/**
 * Create expired trial subscription
 *
 * @param {Object} overrides - Custom fields
 * @returns {Object} Expired trial subscription
 */
function createExpiredTrialSubscription(overrides = {}) {
  const now = new Date();
  const trialEnd = new Date(now.getTime() - (7 * 24 * 60 * 60 * 1000)); // 7 days ago
  const trialStart = new Date(trialEnd.getTime() - (30 * 24 * 60 * 60 * 1000)); // 30 days before end

  return {
    subscription: createFreeSubscription(),
    trial: {
      ends_at: admin.firestore.Timestamp.fromDate(trialEnd),
      started_at: admin.firestore.Timestamp.fromDate(trialStart),
      is_active: false,
      tier_id: 'pro'
    },
    trialEndsAt: admin.firestore.Timestamp.fromDate(trialEnd),
    ...overrides
  };
}

/**
 * Create complete user subscription data
 *
 * @param {string} tier - 'free', 'pro', 'ultra'
 * @param {Object} overrides - Custom fields
 * @returns {Object} Complete user subscription data
 */
function createUserSubscriptionData(tier = 'free', overrides = {}) {
  const tierMap = {
    free: {
      subscriptionStatus: 'free',
      subscriptionTier: 'Free',
      subscription: createFreeSubscription(),
      trial: null
    },
    pro: {
      subscriptionStatus: 'pro',
      subscriptionTier: 'Pro',
      subscription: createProSubscription(),
      trial: null
    },
    ultra: {
      subscriptionStatus: 'ultra',
      subscriptionTier: 'Ultra',
      subscription: createUltraSubscription(),
      trial: null
    },
    trial: createTrialSubscription(25)
  };

  const base = tierMap[tier] || tierMap.free;
  return { ...base, ...overrides };
}

/**
 * Create subscription document (Firestore subcollection)
 *
 * @param {Object} overrides - Custom fields
 * @returns {Object} Subscription document
 */
function createSubscriptionDocument(overrides = {}) {
  const now = new Date();
  const startDate = new Date(now.getTime() - (30 * 24 * 60 * 60 * 1000)); // 30 days ago
  const endDate = new Date(now.getTime() + (335 * 24 * 60 * 60 * 1000)); // ~11 months from now

  const defaults = {
    subscription_id: `sub_${Date.now()}`,
    user_id: 'test-user-001',
    tier_id: 'pro',
    status: 'active',
    plan_type: 'quarterly',
    amount: 499,
    currency: 'INR',
    payment_provider: 'razorpay',
    payment_id: `pay_${Date.now()}`,
    start_date: admin.firestore.Timestamp.fromDate(startDate),
    end_date: admin.firestore.Timestamp.fromDate(endDate),
    auto_renew: true,
    created_at: admin.firestore.FieldValue.serverTimestamp(),
    updated_at: admin.firestore.FieldValue.serverTimestamp()
  };

  return { ...defaults, ...overrides };
}

/**
 * Create cancelled subscription document
 *
 * @param {Object} overrides - Custom fields
 * @returns {Object} Cancelled subscription
 */
function createCancelledSubscription(overrides = {}) {
  const now = new Date();
  const endDate = new Date(now.getTime() + (7 * 24 * 60 * 60 * 1000)); // 7 days from now

  return createSubscriptionDocument({
    status: 'cancelled',
    auto_renew: false,
    cancelled_at: admin.firestore.FieldValue.serverTimestamp(),
    cancellation_reason: 'user_requested',
    end_date: admin.firestore.Timestamp.fromDate(endDate),
    ...overrides
  });
}

module.exports = {
  createSubscription,
  createFreeSubscription,
  createProSubscription,
  createUltraSubscription,
  createSubscriptionWithOverride,
  createBetaSubscription,
  createTrialSubscription,
  createExpiredTrialSubscription,
  createUserSubscriptionData,
  createSubscriptionDocument,
  createCancelledSubscription
};
