/**
 * User Factory
 *
 * Creates test user data for testing purposes.
 * Based on test users from setup-test-users.js but with programmatic generation.
 */

const { admin } = require('../../src/config/firebase');

/**
 * Generate theta data based on skill level and progress
 *
 * @param {string} skillLevel - 'beginner', 'intermediate', 'advanced'
 * @param {number} quizzesCompleted - Number of quizzes completed
 * @returns {Object} Theta data structure
 */
function generateThetaData(skillLevel = 'intermediate', quizzesCompleted = 0) {
  const thetaMap = {
    beginner: -0.5,
    intermediate: 0.0,
    advanced: 0.5
  };

  const baseTheta = thetaMap[skillLevel] || 0.0;
  const percentile = 50 + (baseTheta * 34); // Normal distribution approximation

  return {
    overall_theta: Number(baseTheta.toFixed(2)),
    overall_percentile: Number(percentile.toFixed(1)),
    theta_by_subject: {
      physics: {
        theta: Number((baseTheta + (Math.random() * 0.2 - 0.1)).toFixed(2)),
        se: skillLevel === 'beginner' ? 0.5 : skillLevel === 'intermediate' ? 0.3 : 0.2,
        questions_answered: Math.floor(quizzesCompleted * 1.5)
      },
      chemistry: {
        theta: Number((baseTheta + (Math.random() * 0.2 - 0.1)).toFixed(2)),
        se: skillLevel === 'beginner' ? 0.5 : skillLevel === 'intermediate' ? 0.3 : 0.2,
        questions_answered: Math.floor(quizzesCompleted * 1.5)
      },
      mathematics: {
        theta: Number((baseTheta + (Math.random() * 0.2 - 0.1)).toFixed(2)),
        se: skillLevel === 'beginner' ? 0.5 : skillLevel === 'intermediate' ? 0.3 : 0.2,
        questions_answered: Math.floor(quizzesCompleted * 1.5)
      }
    },
    theta_by_chapter: {
      physics_kinematics: {
        theta: Number((baseTheta + 0.1).toFixed(2)),
        se: 0.25,
        questions_answered: Math.max(5, Math.floor(quizzesCompleted * 0.2))
      },
      chemistry_atomic_structure: {
        theta: Number((baseTheta - 0.1).toFixed(2)),
        se: 0.28,
        questions_answered: Math.max(3, Math.floor(quizzesCompleted * 0.15))
      },
      mathematics_differentiation: {
        theta: Number((baseTheta + 0.05).toFixed(2)),
        se: 0.26,
        questions_answered: Math.max(7, Math.floor(quizzesCompleted * 0.25))
      }
    }
  };
}

/**
 * Create user profile data
 *
 * @param {Object} overrides - Custom fields to override defaults
 * @returns {Object} User profile object
 */
function createUser(overrides = {}) {
  const defaults = {
    userId: `test-user-${Date.now()}`,
    phoneNumber: `+1650555${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`,
    displayName: 'Test User',
    isEnrolledInCoaching: false,
    subscriptionStatus: 'free',
    subscriptionTier: 'Free',
    subscription: {
      tier: 'free',
      status: 'active',
      last_synced: admin.firestore.FieldValue.serverTimestamp()
    },
    overall_theta: 0.0,
    overall_percentile: 50.0,
    theta_by_subject: {
      physics: { theta: 0.0, se: 0.6, questions_answered: 0 },
      chemistry: { theta: 0.0, se: 0.6, questions_answered: 0 },
      mathematics: { theta: 0.0, se: 0.6, questions_answered: 0 }
    },
    theta_by_chapter: {},
    quizzes_completed: 0,
    chapter_practice_completed: 0,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp()
  };

  return { ...defaults, ...overrides };
}

/**
 * Create free tier user
 *
 * @param {Object} overrides - Custom fields to override defaults
 * @returns {Object} Free tier user
 */
function createFreeUser(overrides = {}) {
  const baseUser = createUser({
    subscriptionStatus: 'free',
    subscriptionTier: 'Free',
    subscription: {
      tier: 'free',
      status: 'active',
      last_synced: admin.firestore.FieldValue.serverTimestamp()
    }
  });

  return { ...baseUser, ...overrides };
}

/**
 * Create pro tier user with testing override
 *
 * @param {Object} overrides - Custom fields to override defaults
 * @returns {Object} Pro tier user
 */
function createProUser(overrides = {}) {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + (90 * 24 * 60 * 60 * 1000)); // 90 days

  const baseUser = createUser({
    subscriptionStatus: 'pro',
    subscriptionTier: 'Pro',
    subscription: {
      tier: 'pro',
      status: 'active',
      last_synced: admin.firestore.FieldValue.serverTimestamp(),
      override: {
        type: 'testing',
        tier_id: 'pro',
        granted_by: 'test-factory',
        granted_at: admin.firestore.FieldValue.serverTimestamp(),
        expires_at: admin.firestore.Timestamp.fromDate(expiresAt),
        reason: 'Generated by test factory'
      }
    }
  });

  return { ...baseUser, ...overrides };
}

/**
 * Create ultra tier user with testing override
 *
 * @param {Object} overrides - Custom fields to override defaults
 * @returns {Object} Ultra tier user
 */
function createUltraUser(overrides = {}) {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + (90 * 24 * 60 * 60 * 1000)); // 90 days

  const baseUser = createUser({
    subscriptionStatus: 'ultra',
    subscriptionTier: 'Ultra',
    subscription: {
      tier: 'ultra',
      status: 'active',
      last_synced: admin.firestore.FieldValue.serverTimestamp(),
      override: {
        type: 'testing',
        tier_id: 'ultra',
        granted_by: 'test-factory',
        granted_at: admin.firestore.FieldValue.serverTimestamp(),
        expires_at: admin.firestore.Timestamp.fromDate(expiresAt),
        reason: 'Generated by test factory'
      }
    }
  });

  return { ...baseUser, ...overrides };
}

/**
 * Create trial user (active or expiring)
 *
 * @param {number} daysRemaining - Days until trial expires
 * @param {Object} overrides - Custom fields to override defaults
 * @returns {Object} Trial user
 */
function createTrialUser(daysRemaining = 25, overrides = {}) {
  const now = new Date();
  const trialEnd = new Date(now.getTime() + (daysRemaining * 24 * 60 * 60 * 1000));
  const trialStart = new Date(now.getTime() - ((30 - daysRemaining) * 24 * 60 * 60 * 1000));

  const baseUser = createUser({
    subscriptionStatus: 'pro_trial',
    subscriptionTier: 'Pro',
    subscription: {
      tier: 'pro',
      status: 'trial',
      last_synced: admin.firestore.FieldValue.serverTimestamp()
    },
    trial: {
      ends_at: admin.firestore.Timestamp.fromDate(trialEnd),
      started_at: admin.firestore.Timestamp.fromDate(trialStart),
      is_active: true,
      tier_id: 'pro'
    },
    trialEndsAt: admin.firestore.Timestamp.fromDate(trialEnd)
  });

  return { ...baseUser, ...overrides };
}

/**
 * Create user with specific skill level and progress
 *
 * @param {string} skillLevel - 'beginner', 'intermediate', 'advanced'
 * @param {number} quizzesCompleted - Number of quizzes completed
 * @param {Object} overrides - Custom fields to override defaults
 * @returns {Object} User with specific skill level
 */
function createUserWithProgress(skillLevel = 'intermediate', quizzesCompleted = 50, overrides = {}) {
  const thetaData = generateThetaData(skillLevel, quizzesCompleted);
  const baseUser = createUser({
    ...thetaData,
    quizzes_completed: quizzesCompleted,
    chapter_practice_completed: Math.floor(quizzesCompleted * 0.6)
  });

  return { ...baseUser, ...overrides };
}

module.exports = {
  createUser,
  createFreeUser,
  createProUser,
  createUltraUser,
  createTrialUser,
  createUserWithProgress,
  generateThetaData
};
